#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VIDEO_PATH="$PROJECT_DIR/meditation_visualRohan/ONE_MINS.mp4"
FRONT_SCRIPT="$PROJECT_DIR/Front.py"
SIDE_SCRIPT="$PROJECT_DIR/depth/splitSide.py"
ADJUSTMENT_SCRIPT="$PROJECT_DIR/depth/adjustment_test.py"
ACQUISITION_SCRIPT="$PROJECT_DIR/acquisition"


# Play the video in full screen
echo "Playing meditation video in full screen..."
mpv --fs "$VIDEO_PATH"

# Run the first Python script
echo "Running splitFront.py..."
python3 "$FRONT_SCRIPT"
if [ $? -ne 0 ]; then
    echo "splitFront.py failed. Exiting."
    exit 1
fi

# Run the second Python script
echo "Running splitSide.py..."
python3 "$SIDE_SCRIPT"
if [ $? -ne 0 ]; then
    echo "splitSide.py failed. Exiting."
    exit 1
fi

# Run the third Python script
echo "Running splitSide.py..."
python3 "$ADJUSTMENT_SCRIPT"
if [ $? -ne 0 ]; then
    echo "adjustment_test.py failed. Exiting."
    exit 1
fi

# Run the acquisition script
echo "Running acquisition.sh..."
bash "$ACQUISITION_SCRIPT"
if [ $? -ne 0 ]; then
    echo "acquisition.sh failed. Exiting."
    exit 1
fi

echo "All tasks completed successfully."
exit 0
