#!/bin/bash
#sudo chmod 777 check_radar
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/RADAR/NEW/CHECK" || exit
find . -name cd6_write_check.csv -delete
find . -name Chest_Display.png -delete
sudo python3 Radar_Acquire_NT_Check.py &

sleep 11 && python3 Waveform.py &
sleep 15 && feh Chest_Display.png &
sleep 27 && pidof feh && pkill feh
