#!/bin/bash

# Navigate to the directory where the video is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/video_capture" || exit


# Define the width and height
width=480
height=640

# Launch the first video
#mpv --geometry=${width}x${height}+0+0 seek.avi 
python3 morphing.py & 

# Launch the second video
sleep 5 && mpv --geometry=${width}x${height}+${width}+0 output_morphed_video.mp4
