#!/bin/bash

# Navigate to the directory where the scripts are located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/video_capture" || exit

# Run visual1capture.py in the background
python3 Radar_Analysis.py &

wait

python3 Radar_Animation.py 
